import {
  FileText,
  ShieldCheck,
  AlertTriangle,
  BarChart3,
} from "lucide-react";

import { generateInvestigationReport } from "../services/reports/investigationReport";
import Layout from "../components/Layout";
import { useState } from "react";
import { useInvestigations } from "../context/InvestigationContext";
import { useIssue } from "../context/IssueContext";

import {
  deleteInvestigation,
} from "../services/investigation/investigationSupabaseService";

import {
  Eye,
  Download,
  Trash2,
} from "lucide-react";

import { useNavigate } from "react-router-dom";

export default function Reports() {
  const {
    investigations: reports,
    loadInvestigations,
  } = useInvestigations();

  const { searchQuery } = useIssue();
  const [riskFilter, setRiskFilter] = useState("All");
  const [sortOrder, setSortOrder] = useState("Newest");

  const navigate = useNavigate();

  async function handleDelete(id) {
    const confirmed = window.confirm(
      "Are you sure you want to delete this investigation report?"
    );

    if (!confirmed) return;

    try {
      await deleteInvestigation(id);
      await loadInvestigations();
    } catch (err) {
      console.error(err);
      alert("Failed to delete investigation.");
    }
  }

  function handleView(report) {

      navigate(`/reports/${report.id}`);

  }

  function handleDownload(report) {
    generateInvestigationReport(report);
  }

  const filteredReports = [...reports]
    .filter((report) => {
        const query = searchQuery.toLowerCase();

        const matchesSearch =
          report.fileName?.toLowerCase().includes(query) ||
          report.reportId?.toLowerCase().includes(query) ||
          report.recipients?.some((recipient) =>
            recipient.toLowerCase().includes(query)
          );

        const matchesRisk =
        riskFilter === "All" ||
        report.risk?.toLowerCase() ===
            riskFilter.toLowerCase();

        return matchesSearch && matchesRisk;
    })
    .sort((a, b) => {
        const dateA = new Date(
            a.generatedAt || a.investigatedAt
        );

        const dateB = new Date(
            b.generatedAt || b.investigatedAt
        );

        if (sortOrder === "Newest") {
            return dateB - dateA;
        }

        return dateA - dateB;
    });

  const totalReports = reports.length;

  const highRiskReports = reports.filter(
    (r) => r.risk?.toLowerCase() === "high"
  ).length;

  const reportsWithConfidence = reports.filter(
    (r) => typeof r.confidence === "number"
  );

  const avgConfidence =
    reportsWithConfidence.length === 0
      ? "0%"
      : (
          reportsWithConfidence.reduce(
            (sum, r) => sum + r.confidence,
            0
          ) / reportsWithConfidence.length
        ).toFixed(2) + "%";

  const todayReports = reports.filter((r) => {
    const today = new Date().toDateString();

    return (
      new Date(
        r.investigatedAt
      ).toDateString() === today
          );
  }).length;

  return (
<Layout>

<div className="space-y-8">

      <div>

        <h1 className="text-4xl font-bold text-white">
          Investigation Reports
        </h1>

        <p className="mt-2 text-slate-400">
          Enterprise investigation reports generated by the Alloy Cape forensic engine.
        </p>

      </div>

      <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">

        <KPICard
          icon={FileText}
          title="Total Reports"
          value={totalReports}
          color="text-cyan-400"
        />

        <KPICard
          icon={ShieldCheck}
          title="Average Confidence"
          value={avgConfidence}
          color="text-green-400"
        />

        <KPICard
          icon={AlertTriangle}
          title="High Risk"
          value={highRiskReports}
          color="text-red-400"
        />

        <KPICard
          icon={BarChart3}
          title="Today's Reports"
          value={todayReports}
          color="text-yellow-400"
        />

      </div>

      <div className="rounded-3xl border border-slate-700 bg-[#16213A]">

        {/* Header */}

        <div className="flex flex-col gap-4 border-b border-slate-700 p-6 lg:flex-row lg:items-center lg:justify-between">

        <input
            type="text"
            placeholder="Search Report ID, Recipient, Document..."
            value={searchQuery}

            readOnly
            className="rounded-xl border border-slate-600 bg-[#111B33] px-4 py-3 text-white outline-none focus:border-cyan-400 lg:w-80"
        />

        <div className="flex gap-3">

        <select
            value={riskFilter}
            onChange={(e) => setRiskFilter(e.target.value)}
            className="rounded-xl border border-slate-600 bg-[#111B33] px-4 py-3 text-white"
        >


            <option value="All">All Risks</option>
            <option value="Low">Low</option>
            <option value="Medium">Medium</option>
            <option value="High">High</option>
            
        </select>

        <select
            value={sortOrder}
            onChange={(e) => setSortOrder(e.target.value)}
            className="rounded-xl border border-slate-600 bg-[#111B33] px-4 py-3 text-white"
        >
            <option value="Newest">Newest First</option>
            <option value="Oldest">Oldest First</option>
        </select>

    </div>

</div>

{/* Table */}

  <div className="overflow-x-auto">

    <table className="w-full">

      <thead className="bg-[#111B33] uppercase text-xs tracking-widest text-slate-400">

        <tr className="border-b border-slate-700 text-left text-sm text-slate-400">

          <th className="px-6 py-4">Report ID</th>
          <th className="px-6 py-4">Document</th>
          <th className="px-6 py-4">Recipient</th>
          <th className="px-6 py-4">Risk</th>
          <th className="px-6 py-4">Confidence</th>
          <th className="px-6 py-4">Date</th>
          <th className="px-6 py-4">Actions</th>

        </tr>

      </thead>

      <tbody>

        {filteredReports.length === 0 ? (

          <tr>

            <td
              colSpan={7}
              className="py-20 text-center"
            >

              <h2 className="text-2xl font-bold text-white">

                No Investigation Reports

              </h2>

              <p className="mt-3 text-slate-500">

                Run an investigation to generate your first forensic report.

              </p>

            </td>

          </tr>

        ) : (

          filteredReports.map((report) => (

            <tr
              key={report.id}
              className="border-b border-slate-800 transition hover:bg-cyan-500/5 hover:shadow-inner duration-300"
            >

              <td className="px-6 py-5 font-mono text-cyan-400">

                <span className="rounded-lg bg-cyan-500/10 px-3 py-2 font-mono text-xs text-cyan-400">

                  {report.reportId || report.id.slice(0, 8).toUpperCase()}

                </span>

              </td>

              <td
                className="max-w-[220px] truncate px-6 py-5 text-white"
                title={report.fileName}
              >

                {report.fileName}

              </td>

              <td className="px-6 py-5 text-slate-300">

                {report.recipients?.join(", ") || "-"}

              </td>

              <td className="px-6 py-5">

                <span
                  className={`rounded-full px-3 py-1 text-sm font-semibold ${
                    report.risk === "High"
                      ? "bg-red-500/20 text-red-400"
                      : report.risk === "Medium"
                      ? "bg-yellow-500/20 text-yellow-400"
                      : "bg-green-500/20 text-green-400"
                  }`}
                >

                  {report.risk}

                </span>

              </td>

              <td
                className={`px-6 py-5 font-semibold ${
                  typeof report.confidence === "number"
                    ? report.confidence >= 90
                      ? "text-green-400"
                      : report.confidence >= 70
                      ? "text-yellow-400"
                      : "text-red-400"
                    : "text-slate-500"
                }`}
              >

                {typeof report.confidence === "number"
                  ? `${report.confidence.toFixed(2)}%`
                  : "-"}

              </td>

              <td className="px-6 py-5 text-slate-400">

                {report.generatedAt
                  ? new Date(report.generatedAt).toLocaleDateString()
                  : report.investigatedAt
                  ? new Date(report.investigatedAt).toLocaleDateString()
                  : "-"}

              </td>

              <td className="px-6 py-5">

                <div className="flex gap-2">

                  <button
                    onClick={() => handleView(report)}
                    className="flex items-center gap-2 rounded-lg bg-cyan-500/20 px-4 py-2 text-sm text-cyan-400 transition hover:bg-cyan-500/30"
                  >

                    <Eye size={16} />

                    <span>View</span>

                  </button>

                  <button
                    onClick={() => handleDownload(report)}
                    className="flex items-center gap-2 rounded-lg bg-green-500/20 px-4 py-2 text-sm text-green-400 transition hover:bg-green-500/30"
                  >

                    <Download size={16} />

                    <span>Download</span>

                  </button>

                  <button
                    onClick={() => handleDelete(report.id)}
                    className="flex items-center gap-2 rounded-lg bg-red-500/20 px-4 py-2 text-sm text-red-400 transition hover:bg-red-500/30"
                  >

                    <Trash2 size={16} />

                    <span>Delete</span>

                  </button>

                </div>

              </td>

            </tr>

          ))

        )}

      </tbody>

    </table>

  </div>

</div>

</div>

</Layout>
);
}

function KPICard({
  icon: Icon,
  title,
  value,
  color,
}) {
  return (
    <div className="rounded-2xl border border-slate-700 bg-[#16213A] p-6">

      <div className="mb-4 flex items-center gap-3">

        <Icon
          className={color}
          size={24}
        />

        <span className="text-slate-400">
          {title}
        </span>

      </div>

      <h2 className={`text-3xl font-bold ${color}`}>
        {value}
      </h2>

    </div>
  );
}