import { jsPDF } from "jspdf";

export function generateInvestigationReport(result) {

  if (!result) {
    throw new Error(
      "Investigation result is missing."
    );
  }

  const doc =
    new jsPDF({
      unit: "mm",
      format: "a4",
    });

  const pageWidth =
    doc.internal.pageSize.getWidth();

  const pageHeight =
    doc.internal.pageSize.getHeight();

  const margin = 18;

  const contentWidth =
    pageWidth - margin * 2;

  let y = 18;

  const match =
    result.match ?? {};

  const intelligence =
    result.intelligence ?? {};

  const risk =
    intelligence.risk ??
    result.risk ??
    {};

  const ai =
    result.aiAnalysis ??
    {};

  const confidence =
    intelligence.confidence ??
    result.confidence ??
    0;

  const forensicEvidence =
    result.evidence ??
    [];

  const findings =
    ai.keyFindings ??
    [];

  const recommendations =
    ai.recommendations ??
    intelligence.recommendations ??
    [];

  const possibleCauses =
    ai.possibleCauses ??
    [];

  const caseId =
    result.reportId ??
    (
      "CASE-" +
      new Date().getFullYear() +
      "-" +
      String(Date.now()).slice(-6)
    );

  const dnaId =
    result.dnaId ??
    match.dnaId ??
    "Not Available";

  const recipient =
    result.recipient ??
    match.recipients?.[0] ??
    match.recipient ??
    "Not Available";

  const classification =
    result.classification ??
    match.classification ??
    "Unknown";

  const fileName =
    result.fileName ??
    match.fileName ??
    "Unknown Document";

  const integrity =
    result.integrity ??
    match.integrity ??
    100;

  const riskLevel =
    typeof risk === "object"
      ? risk.level
      : risk;

  const riskScore =
    typeof risk === "object"
      ? risk.score
      : null;

  function checkPageSpace(required = 20) {

    if (
      y + required >
      pageHeight - 18
    ) {

      doc.addPage();

      y = 20;

      addFooter();

    }

  }

  function addFooter() {

    const footerY =
      pageHeight - 10;

    doc.setDrawColor(200);

    doc.line(
      margin,
      footerY - 5,
      pageWidth - margin,
      footerY - 5
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(8);

    doc.setTextColor(100);

    doc.text(
      "Generated by Alloy Cape™",
      margin,
      footerY
    );

    doc.text(
      "Confidential",
      pageWidth / 2,
      footerY,
      {
        align: "center",
      }
    );

    doc.text(
      `Page ${doc.getNumberOfPages()}`,
      pageWidth - margin,
      footerY,
      {
        align: "right",
      }
    );

    doc.setTextColor(0);

  }

  function section(title) {

    checkPageSpace(18);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(14);

    doc.setTextColor(
      20,
      40,
      70
    );

    doc.text(
      title,
      margin,
      y
    );

    y += 8;

    doc.setTextColor(0);

  }

  function paragraphSection(title, text) {

    const lines =
      doc.splitTextToSize(
        String(text ?? ""),
        contentWidth
      );

    const requiredHeight =
      8 +
      (lines.length * 5) +
      10;

    checkPageSpace(requiredHeight);

    section(title);

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(10);

    doc.text(
      lines,
      margin,
      y
    );

    y +=
      Math.max(
        8,
        lines.length * 5
      ) + 8;
  }

  function row(label, value) {

    checkPageSpace(12);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(10);

    doc.text(
      label,
      margin,
      y
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    const wrapped =
      doc.splitTextToSize(
        String(
          value ??
          "Not Available"
        ),
        contentWidth - 48
      );

    doc.text(
      wrapped,
      margin + 48,
      y
    );

    y += Math.max(
      6,
      wrapped.length * 5
    );

  }

  function bulletList(items) {

    if (!items?.length) {

      doc.setFont(
        "helvetica",
        "normal"
      );

      doc.setFontSize(10);

      doc.text(
        "None reported.",
        margin + 4,
        y
      );

      y += 7;

      return;

    }

    items.forEach(
      (item) => {

        checkPageSpace(16);

        const text =
          typeof item === "string"
            ? item
            : item?.description ??
              item?.title ??
              JSON.stringify(item);

        const wrapped =
          doc.splitTextToSize(
            `• ${text}`,
            contentWidth - 8
          );

        doc.setFont(
          "helvetica",
          "normal"
        );

        doc.setFontSize(10);

        doc.text(
          wrapped,
          margin + 3,
          y
        );

        y += Math.max(
          6,
          wrapped.length * 5
        );

      }
    );

  }

  // =====================================================
  // HEADER
  // =====================================================

  doc.setFillColor(
    22,
    33,
    58
  );

  doc.rect(
    0,
    0,
    pageWidth,
    38,
    "F"
  );

  doc.setTextColor(
    255,
    255,
    255
  );

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(23);

  doc.text(
    "ALLOY CAPE",
    pageWidth / 2,
    14,
    {
      align: "center",
    }
  );

  doc.setFontSize(10);

  doc.text(
    "Enterprise Digital Document Attribution",
    pageWidth / 2,
    21,
    {
      align: "center",
    }
  );

  doc.setFontSize(14);

  doc.text(
    "AI-ASSISTED FORENSIC INVESTIGATION REPORT",
    pageWidth / 2,
    30,
    {
      align: "center",
    }
  );

  doc.setTextColor(0);

  y = 47;

  // =====================================================
  // VERDICT
  // =====================================================

  const verified =
    result.success !== false;

  doc.setFillColor(
    verified ? 34 : 220,
    verified ? 197 : 38,
    verified ? 94 : 38
  );

  doc.roundedRect(
    margin,
    y,
    contentWidth,
    13,
    3,
    3,
    "F"
  );

  doc.setTextColor(
    255,
    255,
    255
  );

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(14);

  doc.text(
    verified
      ? "INVESTIGATION COMPLETE"
      : "INVESTIGATION FAILED",
    pageWidth / 2,
    y + 8.5,
    {
      align: "center",
    }
  );

  doc.setTextColor(0);

  y += 22;

  // =====================================================
  // CASE INFORMATION
  // =====================================================

  section(
    "CASE INFORMATION"
  );

  row(
    "Case ID",
    caseId
  );

  row(
    "Investigator",
    result.investigator ??
      "Administrator"
  );

  row(
    "Investigated",
    result.investigatedAt
      ? new Date(
          result.investigatedAt
        ).toLocaleString()
      : new Date().toLocaleString()
  );

  row(
    "Engine",
    result.engine ??
      "Alloy Cape Intelligence Engine"
  );

  row(
    "Engine Version",
    result.version ??
      "3.0"
  );

  y += 3;

  // =====================================================
  // DOCUMENT INFORMATION
  // =====================================================

  section(
    "DOCUMENT INFORMATION"
  );

  row(
    "Document",
    fileName
  );

  row(
    "DNA ID",
    dnaId
  );

  row(
    "Copy ID",
    result.copyId ??
      "Verified Protected Copy"
  );

  row(
    "Recipient",
    recipient
  );

  row(
    "Classification",
    classification
  );

  row(
    "Integrity",
    `${integrity}%`
  );

  row(
    "Issued",
    match.issuedAt
      ? new Date(
          match.issuedAt
        ).toLocaleString()
      : "Not Available"
  );

  y += 3;

  // =====================================================
  // RISK & CONFIDENCE
  // =====================================================

  section(
    "RISK & CONFIDENCE ASSESSMENT"
  );

  row(
    "Risk Level",
    riskLevel ??
      "Not Available"
  );

  row(
    "Risk Score",
    riskScore !== null
      ? `${riskScore}/100`
      : "Not Available"
  );

  row(
    "AI Confidence",
    `${confidence}%`
  );

  row(
    "Tampering",
    result.tampered
      ? "Detected"
      : "Not Detected"
  );

  row(
    "Leak Probability",
    result.leakProbability !==
    undefined
      ? `${result.leakProbability}%`
      : "Not Available"
  );

  y += 3;

  // =====================================================
  // FINGERPRINT
  // =====================================================

  section(
    "DOCUMENT FINGERPRINT"
  );

  const hash =
    match.sha256 ??
    result.sha256 ??
    "Not Available";

  const hashLines =
    doc.splitTextToSize(
      hash,
      contentWidth - 8
    );

  const hashHeight =
    hashLines.length * 5 + 10;

  checkPageSpace(
    hashHeight + 10
  );

  doc.setFillColor(
    245,
    245,
    245
  );

  doc.roundedRect(
    margin,
    y - 3,
    contentWidth,
    hashHeight,
    2,
    2,
    "FD"
  );

  doc.setFont(
    "courier",
    "normal"
  );

  doc.setFontSize(9);

  doc.text(
    hashLines,
    margin + 4,
    y + 3
  );

  y += hashHeight + 7;

  // =====================================================
  // FORENSIC VERIFICATION
  // =====================================================

  section(
    "FORENSIC VERIFICATION"
  );

  bulletList([
    "Document DNA verified against the Alloy Cape Registry.",
    "Protected copy identity verified.",
    "Recipient attribution verified.",
    "Recipient signature verified.",
    "Page count verified.",
    "Text fingerprint verified.",
    result.tampered
      ? "Tampering indicators detected."
      : "No tampering indicators detected.",
  ]);

  y += 3;

  // =====================================================
  // FORENSIC EVIDENCE
  // =====================================================

  section(
    "FORENSIC EVIDENCE"
  );

  if (
    forensicEvidence.length === 0
  ) {

    bulletList([
      "No additional forensic evidence was recorded.",
    ]);

  } else {

    forensicEvidence.forEach(
      (item) => {

        checkPageSpace(18);

        const title =
          item?.title ??
          item?.type ??
          "Evidence";

        const description =
          item?.description ??
          item?.message ??
          "";

        doc.setFont(
          "helvetica",
          "bold"
        );

        doc.setFontSize(10);

        doc.text(
          title,
          margin,
          y
        );

        y += 5;

        doc.setFont(
          "helvetica",
          "normal"
        );

        const wrapped =
          doc.splitTextToSize(
            description,
            contentWidth
          );

        doc.text(
          wrapped,
          margin + 3,
          y
        );

        y += Math.max(
          6,
          wrapped.length * 5
        );

      }
    );

  }

  // =====================================================
  // AI REPORT — HIGHLIGHT
  // =====================================================

  checkPageSpace(35);

  doc.setFillColor(
    15,
    23,
    42
  );

  doc.roundedRect(
    margin,
    y,
    contentWidth,
    18,
    3,
    3,
    "F"
  );

  doc.setTextColor(
    80,
    220,
    180
  );

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(16);

  doc.text(
    "AI INVESTIGATION REPORT",
    pageWidth / 2,
    y + 8,
    {
      align: "center",
    }
  );

  doc.setFontSize(9);

  doc.text(
    "Generated from the Alloy Cape Intelligence Engine",
    pageWidth / 2,
    y + 14,
    {
      align: "center",
    }
  );

  doc.setTextColor(0);

  y += 27;

  // =====================================================
  // AI EXECUTIVE SUMMARY
  // =====================================================

  const executiveSummary =
    ai.executiveSummary ??
    "No AI executive summary was recorded.";

  paragraphSection(
    "AI EXECUTIVE SUMMARY",
    executiveSummary
  );

  // =====================================================
  // AI TECHNICAL ASSESSMENT
  // =====================================================

  const technical =
    ai.technicalAssessment ??
    "No AI technical assessment was recorded.";

  paragraphSection(
    "AI TECHNICAL ASSESSMENT",
    technical
  );

  // =====================================================
  // AI KEY FINDINGS
  // =====================================================

  section(
    "AI KEY FINDINGS"
  );

  bulletList(
    findings
  );

  // =====================================================
  // AI RECOMMENDATIONS
  // =====================================================

  section(
    "AI RECOMMENDED ACTIONS"
  );

  bulletList(
    recommendations
  );

  // =====================================================
  // AI POSSIBLE CAUSES
  // =====================================================

  section(
    "AI POSSIBLE CAUSES"
  );

  bulletList(
    possibleCauses
  );

  // =====================================================
  // FINAL AI VERDICT
  // =====================================================

  checkPageSpace(35);

  const finalAssessment =
    `The Alloy Cape Intelligence Engine assessed this investigation with a confidence of ${confidence}%. ` +
    `The calculated risk level is ${riskLevel ?? "Not Available"}${
      riskScore !== null
        ? ` with a score of ${riskScore}/100`
        : ""
    }. ` +
    `This assessment is based on the verified document identity, recipient attribution, forensic evidence, document integrity, activity history and AI analysis.`;

  checkPageSpace(45);

  section(
    "AI FINAL ASSESSMENT"
  );

  const finalLines =
    doc.splitTextToSize(
      finalAssessment,
      contentWidth - 10
    );

  const finalHeight =
    finalLines.length * 5 + 12;

  doc.setFillColor(
    240,
    248,
    246
  );

  doc.roundedRect(
    margin,
    y - 4,
    contentWidth,
    finalHeight,
    3,
    3,
    "FD"
  );

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.setFontSize(10);

  doc.text(
    finalLines,
    margin + 5,
    y + 3
  );

  y += finalHeight + 8;

  // =====================================================
  // AUDIT INFORMATION
  // =====================================================

  section(
    "AUDIT INFORMATION"
  );

  row(
    "Report ID",
    result.reportId ??
      caseId
  );

  row(
    "Generated",
    result.generatedAt
      ? new Date(
          result.generatedAt
        ).toLocaleString()
      : new Date().toLocaleString()
  );

  row(
    "Platform",
    "Alloy Cape™ Enterprise Digital Document Attribution"
  );

  row(
    "Report Type",
    "AI-Assisted Digital Forensic Investigation"
  );

  // =====================================================
  // FOOTER
  // =====================================================

  const totalPages =
    doc.getNumberOfPages();

  for (
    let page = 1;
    page <= totalPages;
    page++
  ) {

    doc.setPage(page);

    addFooter();

  }

  doc.save(
    `Investigation_Report_${dnaId}.pdf`
  );

}