import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateReportPDF(report) {
  const doc = new jsPDF("p", "mm", "a4");

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let y = 42;

  function checkPageBreak(requiredHeight = 20) {
    if (y + requiredHeight > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
  }

  // =========================
  // Header
  // =========================

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("ALLOY CAPE", 15, 15);

  doc.setFontSize(12);
  doc.text("Document Investigation Report", 15, 23);

  doc.setTextColor(0);

  // =========================
  // Information Table
  // =========================

  autoTable(doc, {
    startY: y,
    head: [["Field", "Value"]],
    body: [
      ["Report ID", report.reportId],
      ["Document", report.document.fileName],
      ["Classification", report.document.classification],
      ["DNA ID", report.document.dnaId],
      ["Recipient", report.document.recipient],
      ["Risk", report.ai.riskLevel],
      ["Risk Score", String(report.ai.riskScore)],
      ["Confidence", `${report.ai.confidence}%`],
      ["AI Model", report.ai.model],
      [
        "Generated",
        new Date(report.ai.generatedAt).toLocaleString(),
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [30, 64, 175],
    },
  });

  y = doc.lastAutoTable.finalY + 10;

  // =========================
  // Section
  // =========================

  function section(title, body) {
    checkPageBreak(30);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);

    doc.text(title, 15, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(
      body || "No information available.",
      180
    );

    checkPageBreak(lines.length * 6);

    doc.text(lines, 15, y);

    y += lines.length * 6 + 8;
  }

  // =========================
  // List
  // =========================

  function list(title, items = []) {
    checkPageBreak(25);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);

    doc.text(title, 15, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    if (!items.length) {
      doc.text("-", 20, y);
      y += 8;
      return;
    }

    items.forEach((item) => {
      const lines = doc.splitTextToSize(item, 170);

      checkPageBreak(lines.length * 6 + 5);

      doc.text("•", 18, y);
      doc.text(lines, 24, y);

      y += lines.length * 6 + 4;
    });

    y += 5;
  }

  // =========================
  // Content
  // =========================

  section("Executive Summary", report.ai.executiveSummary);

  section(
    "Technical Assessment",
    report.ai.technicalAssessment
  );

  list("Key Findings", report.ai.keyFindings);

  list("Recommendations", report.ai.recommendations);

  list("Possible Causes", report.ai.possibleCauses);

  // =========================
  // Footer
  // =========================

  checkPageBreak(15);

  doc.setDrawColor(180);

  doc.line(15, y, pageWidth - 15, y);

  y += 6;

  doc.setFontSize(9);
  doc.setTextColor(100);

  doc.text("Generated by Alloy Cape", 15, y);

  doc.text(
    "AI Model: " + report.ai.model,
    pageWidth - 65,
    y
  );

  doc.save(
    `${report.document.fileName}_Investigation_Report.pdf`
  );
}